### ISSUE TITLE
Route files are not being compiled with babel polyfill

### ISSUE THREAD

**Issue by zooshme** [jesseditson/fs-router#1]
It looks like route files are not being compiled with babel polyfill. The use of ```async``` throws an ```Unexpected token function``` error.

**Comment by jesseditson** [comment]
I'll take a look! Mind posting your .babelrc or config flags and the command you use to run? I'll try to repro and get a fix in!

**Comment by zooshme** [comment]
I don't have a .babelrc file. My understanding is that micro is taking care of babel support for async/await functionality. A quick fix has been to use node 7 and harmony flags. This is what my npm start script looks like ```node --harmony-async-await ./node_modules/.bin/micro``` But I feel this is more of a last resort.

**Comment by jesseditson** [comment]
For sure! in node v7.6+, things should run natively, and below that micro uses async-to-gen to add async/await support. If you're transpiling, what is your deployment target and build process?

**Comment by zooshme** [comment]
I will be deploying to zeit. I'm not sure whether I need a build process as such, my understanding is that micro should take care of it. Am I wrong?

**Comment by jesseditson** [comment]
Mainly what I'm after is a way to reproduce your issue! I'm using this lib on zeit right now without any issues, so I figure there must be something in your setup preventing the routes from being transpiled properly.

**Comment by jesseditson** [comment]
Node async/await is LTS now, and this issue is likely irrelevant. Please re-open if I closed in error!
